server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://${URL_DB_ENV}:${DATABASE_PORT}/${NAME_DB_ENV}
    username: ${USERNAME_DB_ENV}
    password: ${PASSWORD_DB_ENV}
  jpa:
    hibernate:
      ddl-auto: none
      globally-quoted-identifiers: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: off